#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin

where_am_i=$( hostname -s )

#
## When on Ouranos
#

if [ "${where_am_i}" = "ouranos" ]
then
	chown dovecot /etc/letsencrypt/archive/imap.olympe.lurenzu.org/privkey*.pem
	systemctl restart dovecot

	for server in chaos 
	do
		rc=0
		for D in /etc/letsencrypt/archive/imap.olympe.lurenzu.org/ /etc/letsencrypt/live/imap.olympe.lurenzu.org/
		do
			rsync -a --delete $D ${server}:$D
			rc=$?

			RC=$(( $RC + $rc ))
		done

		ssh ${server} "systemctl restart dovecot"
	done
fi

exit $RC
