#!/bin/bash


groupadd -g 1500 mailtasks
useradd -u 1500 -g 1500 -G sa-milt,mail mailtasks

cat > /etc/sudoers.d/mailtasks <<EOS
# rules for batch mailtasks

mailtasks	ALL=(sa-milt)	NOPASSWD:	/usr/bin/sa-learn
mailtasks	ALL=(mail)	NOPASSWD:	/usr/bin/doveadm move *, \
						/usr/bin/doveadm expunge *, \
						/usr/bin/doveadm index *, \
						/usr/bin/doveadm mailbox create *,\
						/usr/bin/doveadm mailbox list * 

mailtasks	ALL=(root)	NOPASSWD:	/opt/mailtasks/createUserSpamDB

EOS

chmod 0400 /etc/sudoers.d/mailtasks
chown root.root /etc/sudoers.d/mailtasks
