#!/bin/bash -p

if [ -r $( dirname $0 )/MailTasksCONFIG ] 
then
	. $( dirname $0 )/MailTasksCONFIG
else
	exit 127
fi

RC=0

[ -d ${LOCKDIR} ] || mkdir ${LOCKDIR}

for SERVER in ${TARGET_SERVERS}
do
	if [ -f ${LOCKDIR}/${SERVER} ]
	then
		echo "Lock file ${LOCKDIR}/${SERVER} found, skipping server ${SERVER}."
	else
		touch ${LOCKDIR}/${SERVER}

		echo "################################################"
		echo "# Backup/sync for ${SERVER}                    #"
		echo "################################################"
		echo ""
		echo ""
		echo ""

		a=1
		rc=19
		while [ $a -le $MAILBOX_SYNC_MAX_ATTEMPTS -a $rc -ne 0 ]
		do
			echo "+    attempt $a"
			/usr/bin/doveadm backup -F ${USER_LIST} remote:${SERVER}.tartar.lurenzu.org
			rc=$?

			a=$(( $a + 1 ))
			echo ""
		done

		RC=$(( $RC + $rc ))
		echo ""
		echo ""

		rm -f ${LOCKDIR}/${SERVER}
	fi
done > ${LOGFILE} 2>&1

[ $RC -ne 0 ] && /bin/cat ${LOGFILE}

exit $RC
