#!/bin/bash
 
DB_SERVER='localhost'
DB_USER='opendmarc'
DB_PASS='0ff137fb818d69eca4def9eda1fedf21d2d7e8c2661011176e315cdb1299e350'
DB_NAME='opendmarc'
WORK_DIR='/var/spool/opendmarc'
REPORT_EMAIL='dmarc@lurenzu.org'
REPORT_ORG='Lurenzu Org'
 
 
/usr/sbin/opendmarc-reports --dbhost=${DB_SERVER} --dbuser=${DB_USER} --dbpasswd=${DB_PASS} --dbname=${DB_NAME} --verbose --interval=86400 --utc --report-email $REPORT_EMAIL --report-org $REPORT_ORG
/usr/sbin/opendmarc-expire --dbhost=${DB_SERVER} --dbuser=${DB_USER} --dbpasswd=${DB_PASS} --dbname=${DB_NAME} --verbose

